<?php
namespace app\models\user;

use dektrium\user\models\Profile AS BaseProfile;


class Profile extends BaseProfile {

    public function rules() {
        return [
            'phone' => ['phone', 'string', 'max' => 255],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
