<?php
namespace app\models\user;

use dektrium\user\models\Profile AS BaseProfile;


class Profile extends BaseProfile {

    public function rules() {
        return [
            'phone' => ['phone', 'string', 'max' => 255],
            'name' => ['name', 'string', 'max' => 255],
            'website' => ['website', 'string', 'max' => 255],
            'public_email' => ['public_email', 'string', 'max' => 255],
            'location' => ['location', 'string', 'max' => 255],
            'bio' => ['location', 'string', 'max' => 255],
            'gravatar_email' => ['location', 'string', 'max' => 255],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
