<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "core_cert".
 *
 * @property int $id
 * @property string $file
 */
class CoreCert extends \yii\db\ActiveRecord
{
    public $file_core;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'core_cert';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['file_core'], 'safe'],
            [['file'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => 'File',
        ];
    }

    public function beforeSave($insert)
    {
        $this->file_core = UploadedFile::getInstance($this, 'file_core');
        if (!empty($this->file_core)) {
            $oldCert = CoreCert::find()->one();
            if(!empty($oldCert)){
                $oldCert->delete();
            }
            $fileName = $this->file_core->name;
            if (!is_dir(Yii::getAlias('@app') . '/web/certs/')) {
                mkdir(Yii::getAlias('@app') . '/web/certs/');
            }
            $this->file_core->saveAs(Yii::getAlias('@app') . '/web/certs/' . $fileName);
            $this->file = $fileName;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
