<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "settings".
 *
 * @property int $id
 * @property string $name
 * @property string $value
 * @property string $type
 */
class Settings extends \yii\db\ActiveRecord
{
    public $file_core;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name','type', 'value'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'value' => 'Значение',
            'type' => 'Тип',
            'file_core' => 'Файл',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->type == 'file') {
            $this->file_core = UploadedFile::getInstance($this, 'file_core');
            if (!empty($this->file_core)) {
                $oldCert = Settings::find()->where(['name' => 'file_core'])->one();
                if(!empty($oldCert)){
                    $oldCert->delete();
                }
                $fileName = $this->file_core->name;
                if (!is_dir(Yii::getAlias('@app') . '/web/certs/')) {
                    mkdir(Yii::getAlias('@app') . '/web/certs/');
                }
                $this->file_core->saveAs(Yii::getAlias('@app') . '/web/certs/' . $fileName);
                $this->value = $fileName;
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
