<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "support".
 *
 * @property int $id
 * @property string $question
 * @property string|null $answer
 * @property string $datecreate
 * @property int $is_active
 * @property string|null $tags
 * @property string|null $category
 */
class Support extends \yii\db\ActiveRecord
{
    public $tagsList =[];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'support';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['question'], 'required'],
            [['question', 'answer'], 'string'],
            [['datecreate','tagsList'], 'safe'],
            [['is_active'], 'integer'],
            [['tags','category'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'question' => 'Вопрос',
            'answer' => 'Ответ',
            'datecreate' => 'Дата создания',
            'is_active' => 'Активность',
            'tags' => 'Теги',
            'category' => 'Категории',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->tagsList){
            $this->tags = implode(',', $this->tagsList);
        }
        $this->datecreate = date('Y-m-d');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
